name = "privateden-oauth"
main = "worker.js"
compatibility_date = "2024-01-01"

# Secrets are set via:
#   wrangler secret put ADMIN_USERNAME
#   wrangler secret put ADMIN_PASSWORD
#   wrangler secret put GITHUB_TOKEN
